### ISSUE TITLE
Missing dependency on rosauth

### ISSUE THREAD

**Issue by VictorLamoine** [RobotWebTools/rosbridge_suite#260]
```bash
Traceback (most recent call last):
  File "/home/victor/code/catkin_workspace/src/rosbridge_suite/rosbridge_server/scripts/rosbridge_websocket", line 43, in <module>
    from rosbridge_server import RosbridgeWebSocket
  File "/home/victor/code/catkin_workspace/src/rosbridge_suite/rosbridge_server/src/rosbridge_server/__init__.py", line 1, in <module>
    from websocket_handler import RosbridgeWebSocket
  File "/home/victor/code/catkin_workspace/src/rosbridge_suite/rosbridge_server/src/rosbridge_server/websocket_handler.py", line 35, in <module>
    from rosauth.srv import Authentication
ImportError: No module named rosauth.srv

```

**Comment by jihoonl** [comment]
rosauth is listed as [run_depend in package.xml](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosbridge_server/package.xml#L25) rosbridge_server.
