### ISSUE TITLE
Error connecting to secure web sockets.

### ISSUE THREAD

**Issue by to4dy** [RobotWebTools/rosbridge_suite#263]
Hello,

I installed everything exactly like one year ago. Connection to non ssl socket works perfectly. Connection to secure socket results in this error message 

In the Browser: 
`Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
`

In NodeJS: 
```
Error connecting to websocket server:  { Error: connect ENOENT wss://127.0.0.1:9090
    at Object.exports._errnoException (util.js:1028:11)
    at exports._exceptionWithHostPort (util.js:1051:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: 'wss://127.0.0.1:9090' }
Connection to websocket server closed.
```
I use the snakeoil key + certificate, with correct read and write rights. 

Did anybody else encounter this Error?

**Comment by to4dy** [comment]
Solved the issue:
 - roslibjs npm package is not up to date, you need to download the package from github (wss fix)
 - openssl does not allow SSLv2 anymore : you can either fix the code or allow ssl2 in openssl
 - For self signed certificates add: process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; in the node javascript code.
