### ISSUE TITLE
[ROS2] Exception subscribing to std_msgs/Bool using roslibjs

### ISSUE THREAD

**Issue by jarledo** [RobotWebTools/rosbridge_suite#444]
When subscribing to a topic of type std_msgs/Bool using websocket_server and roslibjs an exception occurs.

## Expected Behavior
Message should be sent to roslibjs over websocket.

## Actual Behavior
The following exception occurs:
```
[ERROR 1573745083.199161554] [rosbridge_websocket]: Exception calling subscribe callback: 'bool' object has no attribute 'get_fields_and_field_type
s' (callback() at /home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/subscribers.py:192)
```

The entire traceback is:
```
ERROR:tornado.application:Exception in callback <function main.<locals>.<lambda> at 0x7fe4267d5a60>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/home/dev/ros2_ws/install/rosbridge_server/lib/rosbridge_server/rosbridge_websocket", line 303, in <lambda>
    spin_callback = PeriodicCallback(lambda: rclpy.spin_once(rosbridge_websocket_node, timeout_sec=0.01), 100)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/__init__.py", line 169, in spin_once
    executor.spin_once(timeout_sec=timeout_sec)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/executors.py", line 671, in spin_once
    raise handler.exception()
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/task.py", line 206, in __call__
    self._handler.send(None)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/executors.py", line 393, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/executors.py", line 319, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/executors.py", line 116, in await_or_execute
    return callback(*args)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/subscribers.py", line 189, in callback
    callback(outgoing)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/capabilities/subscribe.py", line 164, in on_msg
    self.handler.handle_message(msg)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/subscription_modifiers.py", line 70, in
handle_message
    self.publish(msg)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/capabilities/subscribe.py", line 153, in _publis$
    self.publish(message, self.fragment_size, self.compression)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/capabilities/subscribe.py", line 329, in publish
    outgoing_msg["msg"] = message.get_json_values()
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/outgoing_message.py", line 18, in get_j$
on_values
    self._json_values = extract_json_values(self._message)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/message_conversion.py", line 136, in ex$
ract_values
    return _from_inst(inst, rostype)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/message_conversion.py", line 200, in _f$
om_inst
    return _from_object_inst(inst, rostype)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/message_conversion.py", line 227, in _f$
om_object_inst
    msg[field_name] = _from_inst(field_inst, field_rostype)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/message_conversion.py", line 200, in _f$
om_inst
    return _from_object_inst(inst, rostype)
  File "/home/dev/ros2_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/message_conversion.py", line 225, in _f$
om_object_inst
    for field_name, field_rostype in inst.get_fields_and_field_types().items():
AttributeError: 'bool' object has no attribute 'get_fields_and_field_types'
```

By digging a bit I figured out that adding `"boolean"` to `ros_primitive_types` in [message_conversion.py:75](https://github.com/RobotWebTools/rosbridge_suite/blob/3f8b3d1b0a80bf78be34e553c6f728e63f802eec/rosbridge_library/src/rosbridge_library/internal/message_conversion.py#L75) fixes the problem. This is probably not the the appropriate fix, though I haven't gone any deeper to find the root cause.

## Steps to Reproduce the Problem

  1. Start websocker server by running `ros2 run rosbridge_server rosbridge_websocket`
  2. Open following html file:
```
<!DOCTYPE html>
<html lang="en">

<head>
  <script src="https://static.robotwebtools.org/roslibjs/current/roslib.js"></script>
</head>

<body>
  <script>
    var ros = new ROSLIB.Ros();
    ros.connect("ws://localhost:9090");

    var listener = new ROSLIB.Topic({
      ros: ros,
      name: '/my_bool',
      messageType: 'std_msgs/msg/Bool'
    });

    listener.subscribe(function (message) {
      console.log('Received message');
      console.log(message);
    });
  </script>
</body>

</html>
```
  3. Publish a std_msgs/Bool by running: `ros2 topic pub -r 1.0 /my_bool std_msgs/Bool "{data: True}"`
  4. Exception occurs

## Specifications

  - ROS Version: dashing
  - OS Version: Ubuntu 18.04 running Ubuntu 18.04 Docker image
  - Rosbridge Version: latest develop branch

**Comment by jarledo** [comment]
To add to this I experienced the same issue going the other way, by publishing to a service that contains a bool value from roslibjs. The relevant javascript looks like this:
```
var setStateClient = new ROSLIB.Service({
        ros: ros,
        name: '/set_state',
        serviceType: 'my_custom_interfaces/src/SetState'
      });

      var request = new ROSLIB.ServiceRequest({
        state: "a_state",
        value: true
      });

      setStateClient.callService(request, function (result) {
        console.log("Got request response");
        console.log(result);
      });
```
The I receive this error message:
```
[ERROR] [rosbridge_websocket]: [Client 0] [id: call_service:/set_state:2] call_service FieldTypeMismatchException: my_custom_interfaces/SetState_Request message requires a boolean for field value, but got a <class 'bool'>
```

Again I was able to work around the issue by adding two lines to [message_conversion.py:286](https://github.com/RobotWebTools/rosbridge_suite/blob/85ca9d450937e50a4129923cc720078a12b8e4f9/rosbridge_library/src/rosbridge_library/internal/message_conversion.py#L286):
```
if rostype == "boolean":
    rostype = "bool"
```

Someone with more intimate knowledge of the code base might be able to pinpoint a better fix for the issue? Or is it rather a problem with roslibjs?
