### ISSUE TITLE
Process dies when launching rosbridge_websocket.launch

### ISSUE THREAD

**Issue by cristea** [RobotWebTools/rosbridge_suite#486]
## Expected Behavior
Until now i could run the rosbridge_websocket.launch in the package rosbridge_server without any modification and errors. 

## Actual Behavior
After launching the launch file the process dies:

```console
me@ipc002:~$ roslaunch rosbridge_server rosbridge_websocket.launch 
... logging to /home/me/.ros/log/f7444f98-83b2-11ea-986b-645d863a89e1/roslaunch-ipc002-1591.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ipc002:45789/

SUMMARY
========

PARAMETERS
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 0.0.0.0
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/bson_only_mode: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 10
 * /rosbridge_websocket/use_compression: False
 * /rosbridge_websocket/websocket_external_port: 9090
 * /rosbridge_websocket/websocket_ping_interval: 0
 * /rosbridge_websocket/websocket_ping_timeout: 30
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)

auto-starting new master
process[master]: started with pid [1603]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f7444f98-83b2-11ea-986b-645d863a89e1
process[rosout-1]: started with pid [1618]
started core service [/rosout]
process[rosbridge_websocket-2]: started with pid [1630]
process[rosapi-3]: started with pid [1638]
2020-04-21 11:32:07+0200 [-] Log opened.
2020-04-21 11:32:08+0200 [-] Traceback (most recent call last):
2020-04-21 11:32:08+0200 [-]   File "/opt/ros/kinetic/lib/rosbridge_server/rosbridge_websocket", line 48, in <module>
2020-04-21 11:32:08+0200 [-]     from rosbridge_server import ClientManager
2020-04-21 11:32:08+0200 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_server/__init__.py", line 2, in <module>
2020-04-21 11:32:08+0200 [-]     from .websocket_handler import RosbridgeWebSocket
2020-04-21 11:32:08+0200 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_server/websocket_handler.py", line 49, in <module>
2020-04-21 11:32:08+0200 [-]     from rosbridge_library.rosbridge_protocol import RosbridgeProtocol
2020-04-21 11:32:08+0200 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_library/rosbridge_protocol.py", line 34, in <module>
2020-04-21 11:32:08+0200 [-]     from rosbridge_library.protocol import Protocol
2020-04-21 11:32:08+0200 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_library/protocol.py", line 40, in <module>
2020-04-21 11:32:08+0200 [-]     from rosbridge_library.util import json, bson
2020-04-21 11:32:08+0200 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_library/util/__init__.py", line 19, in <module>
2020-04-21 11:32:08+0200 [-]     import bson
2020-04-21 11:32:08+0200 [-] ImportError: No module named bson
[rosbridge_websocket-2] process has died [pid 1630, exit code 1, cmd /opt/ros/kinetic/lib/rosbridge_server/rosbridge_websocket __name:=rosbridge_websocket __log:=/home/gessmann/.ros/log/f7444f98-83b2-11ea-986b-645d863a89e1/rosbridge_websocket-2.log].
log file: /home/gessmann/.ros/log/f7444f98-83b2-11ea-986b-645d863a89e1/rosbridge_websocket-2*.log
^C[rosapi-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

## Steps to Reproduce the Problem

  1. Today i made a apt-get upgrade
```
Start-Date: 2020-04-21  08:32:10
Commandline: apt-get dist-upgrade
Requested-By: me (1000)
Upgrade: ros-kinetic-interactive-markers:amd64 (1.11.4-0xenial-20200109-041224+0000, 1.11.5-1xenial-20200406-132203+0000), python-rosdistro:amd64 (0.8.0-100, 0.8.1-100), ros-kinetic-desktop:amd64 (1.3.2-0xenial-20200323-230404+0000, 1.3.2-0xenial-20200406-155053+0000), python-catkin-pkg-modules:amd64 (0.4.16-1, 0.4.17-1), ros-kinetic-rviz-plugin-tutorials:amd64 (0.10.3-0xenial-20200323-033053+0000, 0.10.3-0xenial-20200406-151446+0000), ros-kinetic-rqt-rviz:amd64 (0.5.10-0xenial-20200323-033006+0000, 0.5.10-0xenial-20200406-151429+0000), ros-kinetic-desktop-full:amd64 (1.3.2-0xenial-20200323-230520+0000, 1.3.2-0xenial-20200406-160210+0000), ros-kinetic-rosbridge-library:amd64 (0.11.4-1xenial-20200220-213258+0000, 0.11.5-1xenial-20200413-135517+0000), ros-kinetic-viz:amd64 (1.3.2-0xenial-20200323-041109+0000, 1.3.2-0xenial-20200406-154855+0000), ros-kinetic-rosbridge-suite:amd64 (0.11.4-1xenial-20200220-214055+0000, 0.11.5-1xenial-20200413-140413+0000), python-catkin-pkg:amd64 (0.4.16-100, 0.4.17-100), ros-kinetic-simulators:amd64 (1.3.2-0xenial-20200323-043047+0000, 1.3.2-0xenial-20200406-155930+0000), ros-kinetic-librviz-tutorial:amd64 (0.10.3-0xenial-20200323-032735+0000, 0.10.3-0xenial-20200406-151251+0000), ros-kinetic-urdf-tutorial:amd64 (0.3.0-1xenial-20200323-033234+0000, 0.3.0-1xenial-20200406-151115+0000), ros-kinetic-rosbridge-server:amd64 (0.11.4-1xenial-20200220-213832+0000, 0.11.5-1xenial-20200413-140154+0000), ros-kinetic-rviz-python-tutorial:amd64 (0.10.3-0xenial-20200323-033103+0000, 0.10.3-0xenial-20200406-151539+0000), ros-kinetic-interactive-marker-tutorials:amd64 (0.10.3-0xenial-20200109-042013+0000, 0.10.3-0xenial-20200406-140711+0000), ros-kinetic-rviz:amd64 (1.12.17-0xenial-20200323-025037+0000, 1.12.17-0xenial-20200406-141050+0000), file-roller:amd64 (3.16.5-0ubuntu1.3, 3.16.5-0ubuntu1.4), code:amd64 (1.44.1-1586789296, 1.44.2-1587059832), ros-kinetic-rosbridge-msgs:amd64 (0.11.4-1xenial-20200220-213334+0000, 0.11.5-1xenial-20200413-135822+0000), ros-kinetic-rqt-robot-plugins:amd64 (0.5.7-0xenial-20200323-040554+0000, 0.5.7-0xenial-20200406-154635+0000), ros-kinetic-visualization-tutorials:amd64 (0.10.3-0xenial-20200323-230242+0000, 0.10.3-0xenial-20200406-151959+0000), ros-kinetic-rosapi:amd64 (0.11.4-1xenial-20200220-213726+0000, 0.11.5-1xenial-20200413-135810+0000), python-rosdistro-modules:amd64 (0.8.0-1, 0.8.1-1)
End-Date: 2020-04-21  08:32:30
```
  2. then i did a autoremove because apt proposed to do it. It removes something with bson. Which is exactly the error message it get. But i dont know if it only removed an old version or all versions of bson.

```
Start-Date: 2020-04-21  08:40:37
Commandline: apt autoremove
Requested-By: me (1000)
Remove: libgstreamer0.10-0:amd64 (0.10.36-1.5ubuntu1), linux-headers-4.15.0-76-generic:amd64 (4.15.0-76.86~16.04.1), linux-modules-extra-4.15.0-76-generic:amd64 (4.15.0-76.86~16.04.1), python-bson:amd64 (3.2-1build1), python-bson-ext:amd64 (3.2-1build1), linux-headers-4.4.0-176:amd64 (4.4.0-176.206), gstreamer0.10-tools:amd64 (0.10.36-1.5ubuntu1), linux-modules-4.15.0-76-generic:amd64 (4.15.0-76.86~16.04.1), linux-headers-4.15.0-76:amd64 (4.15.0-76.86~16.04.1), linux-image-4.15.0-76-generic:amd64 (4.15.0-76.86~16.04.1), linux-headers-4.4.0-176-generic:amd64 (4.4.0-176.206)
End-Date: 2020-04-21  08:40:53
```
  
3. roslaunch rosbridge_server rosbridge_websocket.launch without any modification in the launch file.

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): kinetic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): DISTRIB_CODENAME=xenial
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): <version>0.11.5</version>
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): [twisted, version 16.0.0]

**Comment by cristea** [comment]
Reinstalling python-bson and python-bson-ext solves the issue.

I think the issue is in the package dependencies?

**Comment by mvollrath** [comment]
Duplicate #484 

You can workaround this by installing any missing libraries, e.g. python-bson
