### ISSUE TITLE
Rosbridge server failed to launch, missing dependency

### ISSUE THREAD

**Issue by csorvagep** [RobotWebTools/rosbridge_suite#491]
After installation `apt install ros-melodic-rosbridge-suite` and launch `roslaunch rosbridge_server rosbridge_websocket.launch` failed to start with error:

```
2020-04-27 21:32:39+0200 [-] Log opened.
2020-04-27 21:32:39+0200 [-] Traceback (most recent call last):
2020-04-27 21:32:39+0200 [-]   File "/opt/ros/melodic/lib/rosbridge_server/rosbridge_websocket", line 48, in <module>
2020-04-27 21:32:39+0200 [-]     from rosbridge_server import ClientManager
2020-04-27 21:32:39+0200 [-]   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_server/__init__.py", line 2, in <module>
2020-04-27 21:32:39+0200 [-]     from .websocket_handler import RosbridgeWebSocket
2020-04-27 21:32:39+0200 [-]   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_server/websocket_handler.py", line 43, in <module>
2020-04-27 21:32:39+0200 [-]     from tornado import version_info as tornado_version_info
2020-04-27 21:32:39+0200 [-] ImportError: No module named tornado
```
After install python-tornado and python-bson websocket server starts.

## Expected Behavior
Install python tornado and bson along with rosbridge.

## Actual Behavior
No installation, and dependency not set.

## Steps to Reproduce the Problem

  1. Install ROS
  1. install rosbridge-suite
  1. launch websocket server

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): bionic
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.5
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 17.9.0

**Comment by mvollrath** [comment]
Duplicate #484
