### ISSUE TITLE
Fragementation does not work in BSON mode

### ISSUE THREAD

**Issue by PapeCoding** [RobotWebTools/rosbridge_suite#571]
## Expected Behavior
Fragmentation works the same in JSON and BSON mode

## Actual Behavior
Fragmentation works in JSON, but not in BSON mode. While running a lot of stack traces are generated.

## Steps to Reproduce the Problem

  1. Start rosbridge in TCP mode with BSON and subscribe to a topic while requesting fragmentation
  2. See stack traces
  ```sh
  rosbridge_1  | Traceback (most recent call last):
rosbridge_1  |   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_library/internal/subscription_modifiers.py", line 164, in run
rosbridge_1  |     MessageHandler.handle_message(self, msg)
rosbridge_1  |   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_library/internal/subscription_modifiers.py", line 73, in handle_message
rosbridge_1  |     self.publish(msg)
rosbridge_1  |   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_library/capabilities/subscribe.py", line 154, in _publish
rosbridge_1  |     self.publish(message, self.fragment_size, self.compression)
rosbridge_1  |   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_library/capabilities/subscribe.py", line 342, in publish
rosbridge_1  |     self.protocol.send(outgoing_msg)
rosbridge_1  |   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_library/protocol.py", line 269, in send
rosbridge_1  |     self.outgoing(bson.BSON.encode(fragment))
rosbridge_1  |   File "/usr/lib/python2.7/dist-packages/bson/__init__.py", line 1027, in encode
rosbridge_1  |     return cls(_dict_to_bson(document, check_keys, codec_options))
rosbridge_1  | InvalidStringData: strings in documents must be valid UTF-8: '\x91b\x01\x00\x02topic\x00\x0f\x00\x00\x00/pioneer/Image\x00\x03msg\x00]b\x01\x00\x03header\x00>\x00\x00\x00\x03stamp\x00\x1a\x00\x00\x00\x10secs\x00\x00\x00\x00\x00\x10nsecs\x00\x00\x00\x00\x00\x00\x02frame_id\x00\x01\x00\x00\x00\x00\x10seq\x00\xed\x01\x00\x00\x00\x05data\x00\xf6a\x01\x00\x00\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01[...]'
  ```

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): bionic
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.13
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): [Twisted, version 17.9.0]

**Comment by PapeCoding** [comment]
This was actually tested on #545, but seems to be related to the original repo as well.

**Comment by PapeCoding** [comment]
As far as I know: Still relevant.
