### ISSUE TITLE
Can't request message details of common messages

### ISSUE THREAD

**Issue by GiteZz** [RobotWebTools/rosbridge_suite#688]
**Description**

When trying to use the RosAPI to request message details I get an exception in the rosapi node. This happens with a common messages included with ROS2. 

- Library Version: Latest commit in ROS2 branch (67442076c90922b39b21c33908e892a3929daff5)
- ROS Version: Galactic
- Platform / OS: Ubuntu 20.04 (Running in Docker)

**Steps To Reproduce**

`ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{type: geometry_msgs/Twist}"`

Same happens with the std_msgs:

`ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{type: std_msgs/Float32}"`

**Expected Behavior**

Get the message details for the requested message type.

**Actual Behavior**

```
[rosapi_node-2] Traceback (most recent call last):
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/rosapi/rosapi_node", line 322, in <module>
[rosapi_node-2]     main()
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/rosapi/rosapi_node", line 313, in main
[rosapi_node-2]     rclpy.spin(node)
[rosapi_node-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/__init__.py", line 196, in spin
[rosapi_node-2]     executor.spin_once()
[rosapi_node-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 707, in spin_once
[rosapi_node-2]     raise handler.exception()
[rosapi_node-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
[rosapi_node-2]     self._handler.send(None)
[rosapi_node-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 415, in handler
[rosapi_node-2]     await call_coroutine(entity, arg)
[rosapi_node-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 369, in _execute_service
[rosapi_node-2]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[rosapi_node-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 107, in await_or_execute
[rosapi_node-2]     return callback(*args)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/rosapi/rosapi_node", line 225, in get_message_details
[rosapi_node-2]     dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 98, in get_typedef_recursive
[rosapi_node-2]     return _get_typedefs_recursive(type, [])
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 225, in _get_typedefs_recursive
[rosapi_node-2]     return _get_subtypedefs_recursive(typedef, typesseen)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 235, in _get_subtypedefs_recursive
[rosapi_node-2]     typedefs = typedefs + _get_typedefs_recursive(fieldtype, typesseen)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 223, in _get_typedefs_recursive
[rosapi_node-2]     typedef = get_typedef(type)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 78, in get_typedef
[rosapi_node-2]     return _get_typedef(instance)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 164, in _get_typedef
[rosapi_node-2]     fieldtypes.append(_type_name(field_type, field_instance))
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 253, in _type_name
[rosapi_node-2]     return _type_name_from_instance(instance)
[rosapi_node-2]   File "/workspaces/mono/ws/install/rosapi/lib/python3.8/site-packages/rosapi/objectutils.py", line 257, in _type_name_from_instance
[rosapi_node-2]     mod = instance.__module__
[rosapi_node-2] AttributeError: 'float' object has no attribute '__module__'
```

**Comment by GiteZz** [comment]
I've done a bit of debugging to help you guys and I think the definition might have changed from float32/float64 to float/double. If I change the atomics in objectutiles.py from 

```
atomics = [
    "bool",
    "byte",
    "int8",
    "uint8",
    "int16",
    "uint16",
    "int32",
    "uint32",
    "int64",
    "uint64",
    "float32",
    "float64",
    "string",
]
```

to 

```
atomics = [
    "bool",
    "byte",
    "int8",
    "uint8",
    "int16",
    "uint16",
    "int32",
    "uint32",
    "int64",
    "uint64",
    "float",
    "double",
    "string",
]
```

my problems disapear 

** Edit **

Apparently bool changed to boolean and arrays are different too. 

This is what I changed in _get_typedef()

```
        if field_type[:9]=='sequence<':

            arraylen = 0
            field_type = field_type[9:][:-1]
```

Obviously this is not a final solution but it got me working again

**Comment by jtbandes** [comment]
Thanks! Would you be interested in preparing a PR and some tests to fix the issue?

**Comment by scottbell** [comment]
Just ran into this again with humble. Calling:
`ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{type: std_msgs/Float32}"`
causes rosbridge to crash:
```
 $ ros2 launch rosbridge_server rosbridge_websocket_launch.xml 
[INFO] [launch]: All log files can be found below /home/scott/.ros/log/2023-01-06-12-05-52-599792-rosmachine-4566
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rosbridge_websocket-1]: process started with pid [4567]
[INFO] [rosapi_node-2]: process started with pid [4569]
[rosbridge_websocket-1] [INFO] [1673003153.749749059] [rosbridge_websocket]: Rosbridge WebSocket server started on port 9090
[rosapi_node-2] Traceback (most recent call last):
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 329, in <module>
[rosapi_node-2]     main()
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 321, in main
[rosapi_node-2]     rclpy.spin(node)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
[rosapi_node-2]     executor.spin_once()
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 713, in spin_once
[rosapi_node-2]     raise handler.exception()
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[rosapi_node-2]     self._handler.send(None)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
[rosapi_node-2]     await call_coroutine(entity, arg)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 372, in _execute_service
[rosapi_node-2]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[rosapi_node-2]     return callback(*args)
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 228, in get_message_details
[rosapi_node-2]     dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 98, in get_typedef_recursive
[rosapi_node-2]     return _get_typedefs_recursive(type, [])
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 223, in _get_typedefs_recursive
[rosapi_node-2]     typedef = get_typedef(type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 78, in get_typedef
[rosapi_node-2]     return _get_typedef(instance)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 164, in _get_typedef
[rosapi_node-2]     fieldtypes.append(_type_name(field_type, field_instance))
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 253, in _type_name
[rosapi_node-2]     return _type_name_from_instance(instance)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 257, in _type_name_from_instance
[rosapi_node-2]     mod = instance.__module__
[rosapi_node-2] AttributeError: 'float' object has no attribute '__module__'. Did you mean: '__mod__'?
[ERROR] [rosapi_node-2]: process has died [pid 4569, exit code 1, cmd '/opt/ros/humble/lib/rosapi/rosapi_node --ros-args -r __node:=rosapi --params-file /tmp/launch_params_2df8zmzu --params-file /tmp/launch_params_m6j5dj79 --params-file /tmp/launch_params_tg0uwis_'].
```

Using @GiteZz's fix, I was able to get a bit further, but now crashing asking about `rcl_interfaces/msg/ParameterEvent}`. E.g.,:
`ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{type: rcl_interfaces/msg/ParameterEvent}"`
causes:
```
$ ros2 launch rosbridge_server rosbridge_websocket_launch.xml 
[INFO] [launch]: All log files can be found below /home/scott/.ros/log/2023-01-06-12-11-30-370701-rosmachine-4691
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rosbridge_websocket-1]: process started with pid [4692]
[INFO] [rosapi_node-2]: process started with pid [4694]
[rosbridge_websocket-1] [INFO] [1673003491.543589196] [rosbridge_websocket]: Rosbridge WebSocket server started on port 9090
[rosapi_node-2] Traceback (most recent call last):
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 329, in <module>
[rosapi_node-2]     main()
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 321, in main
[rosapi_node-2]     rclpy.spin(node)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
[rosapi_node-2]     executor.spin_once()
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 713, in spin_once
[rosapi_node-2]     raise handler.exception()
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[rosapi_node-2]     self._handler.send(None)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
[rosapi_node-2]     await call_coroutine(entity, arg)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 372, in _execute_service
[rosapi_node-2]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[rosapi_node-2]     return callback(*args)
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 228, in get_message_details
[rosapi_node-2]     dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 97, in get_typedef_recursive
[rosapi_node-2]     return _get_typedefs_recursive(type, [])
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 227, in _get_typedefs_recursive
[rosapi_node-2]     return _get_subtypedefs_recursive(typedef, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 237, in _get_subtypedefs_recursive
[rosapi_node-2]     typedefs = typedefs + _get_typedefs_recursive(fieldtype, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 227, in _get_typedefs_recursive
[rosapi_node-2]     return _get_subtypedefs_recursive(typedef, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 237, in _get_subtypedefs_recursive
[rosapi_node-2]     typedefs = typedefs + _get_typedefs_recursive(fieldtype, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 227, in _get_typedefs_recursive
[rosapi_node-2]     return _get_subtypedefs_recursive(typedef, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 237, in _get_subtypedefs_recursive
[rosapi_node-2]     typedefs = typedefs + _get_typedefs_recursive(fieldtype, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 225, in _get_typedefs_recursive
[rosapi_node-2]     typedef = get_typedef(type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 76, in get_typedef
[rosapi_node-2]     instance = ros_loader.get_message_instance(type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/ros_loader.py", line 91, in get_message_instance
[rosapi_node-2]     cls = get_message_class(typestring)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/ros_loader.py", line 78, in get_message_class
[rosapi_node-2]     return _get_msg_class(typestring)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/ros_loader.py", line 122, in _get_msg_class
[rosapi_node-2]     return _get_class(typestring, subname, _loaded_msgs, _msgs_lock)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/ros_loader.py", line 163, in _get_class
[rosapi_node-2]     modname, classname = _splittype(typestring)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/ros_loader.py", line 213, in _splittype
[rosapi_node-2]     raise InvalidTypeStringException(typestring)
[rosapi_node-2] rosbridge_library.internal.ros_loader.InvalidTypeStringException: octet is not a valid type string
[ERROR] [rosapi_node-2]: process has died [pid 4694, exit code 1, cmd '/opt/ros/humble/lib/rosapi/rosapi_node --ros-args -r __node:=rosapi --params-file /tmp/launch_params_eoskae9r --params-file /tmp/launch_params_oehzpv9e --params-file /tmp/launch_params_nq64wis7'].
```

**Comment by brag00n** [comment]
Hello, I have got the same issue using [roslibpy API](https://roslibpy.readthedocs.io/en/latest/examples.html#querying-ros-api) call. E.g.:
`roslibpy.Ros.get_message_details('geometry_msgs/msg/PoseWithCovarianceStamped')`
cause:

```
[rosapi_node-2] Traceback (most recent call last):
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 329, in <module>
[rosapi_node-2]     main()
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 321, in main
[rosapi_node-2]     rclpy.spin(node)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
[rosapi_node-2]     executor.spin_once()
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 713, in spin_once
[rosapi_node-2]     raise handler.exception()
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[rosapi_node-2]     self._handler.send(None)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
[rosapi_node-2]     await call_coroutine(entity, arg)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 372, in _execute_service
[rosapi_node-2]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[rosapi_node-2]     return callback(*args)
[rosapi_node-2]   File "/opt/ros/humble/lib/rosapi/rosapi_node", line 228, in get_message_details
[rosapi_node-2]     dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 98, in get_typedef_recursive
[rosapi_node-2]     return _get_typedefs_recursive(type, [])
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 225, in _get_typedefs_recursive
[rosapi_node-2]     return _get_subtypedefs_recursive(typedef, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 235, in _get_subtypedefs_recursive
[rosapi_node-2]     typedefs = typedefs + _get_typedefs_recursive(fieldtype, typesseen)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 223, in _get_typedefs_recursive
[rosapi_node-2]     typedef = get_typedef(type)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 78, in get_typedef
[rosapi_node-2]     return _get_typedef(instance)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 164, in _get_typedef
[rosapi_node-2]     fieldtypes.append(_type_name(field_type, field_instance))
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 253, in _type_name
[rosapi_node-2]     return _type_name_from_instance(instance)
[rosapi_node-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosapi/objectutils.py", line 257, in _type_name_from_instance
[rosapi_node-2]     mod = instance.__module__
[rosapi_node-2] AttributeError: 'numpy.ndarray' object has no attribute '__module__'. Did you mean: '__mod__'?

```

**Comment by MartinDong** [comment]
so，the question how to make
