### ISSUE TITLE
ros2 rosbridge_websocket, if use param --address,  there will be errors

### ISSUE THREAD

**Issue by JunlingQin** [RobotWebTools/rosbridge_suite#736]
**Description**

- Library Version:
- ROS Version: ros2
- Platform / OS: Ubuntu 20.04.4

**Steps To Reproduce**

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/rosbridge_server/rosbridge_websocket", line 335, in <module>
    main()
  File "/opt/ros/galactic/lib/rosbridge_server/rosbridge_websocket", line 320, in main
    node = RosbridgeWebsocketNode()
  File "/opt/ros/galactic/lib/rosbridge_server/rosbridge_websocket", line 169, in __init__
    address = int(sys.argv[idx])
ValueError: invalid literal for int() with base 10: ''

**Expected Behavior**

**Actual Behavior**

**Comment by achim-k** [comment]
Fixed by #780
