### ISSUE TITLE
Issue calling `/rosapi/MessageDetails`: KeyError: 'check_fields'

### ISSUE THREAD

**Issue by sebabouche** [RobotWebTools/rosbridge_suite#976]
**Description**
I had an issue trying to get a common message definition through the `rosbridge` server.  
So I tried to mimic it with the command line and it bugged similarly. 

- Library Version: 2.1.0
- ROS Version: Jazzy
- Platform / OS: Ubuntu 24.04.1 LTS

**Steps To Reproduce**
```
ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{'type': 'sensor_msgs/JointState'}"
```
or
```
ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{type: 'sensor_msgs/JointState'}"
```

**Expected Behavior**
I would expect to get something like:

```
std_msgs/Header header
string[] name
float64[] position
float64[] velocity
float64[] effort
```

**Actual Behavior**

These are the logs I get, with a `KeyError: 'check_fields'`

```
[rosapi_node-5] /usr/lib/python3/dist-packages/apt/cache.py:215: Warning: W:Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1, W:Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1, W:Target DEP-11 (main/dep11/Components-arm64.yml) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1, W:Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1
[rosapi_node-5]   self._depcache = apt_pkg.DepCache(self._cache)
[rosapi_node-5] Traceback (most recent call last):
[rosapi_node-5]   File "/opt/ros/jazzy/lib/rosapi/rosapi_node", line 329, in <module>
[rosapi_node-5]     main()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/rosapi/rosapi_node", line 321, in main
[rosapi_node-5]     rclpy.spin(node)
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/__init__.py", line 244, in spin
[rosapi_node-5]     executor.spin_once()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 827, in spin_once
[rosapi_node-5]     self._spin_once_impl(timeout_sec)
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 822, in _spin_once_impl
[rosapi_node-5]     raise handler.exception()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/task.py", line 239, in __call__
[rosapi_node-5]     self._handler.send(None)
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 508, in handler
[rosapi_node-5]     await call_coroutine()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 447, in _execute
[rosapi_node-5]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[rosapi_node-5]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 111, in await_or_execute
[rosapi_node-5]     return callback(*args)
[rosapi_node-5]            ^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/rosapi/rosapi_node", line 228, in get_message_details
[rosapi_node-5]     dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)
[rosapi_node-5]                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 115, in get_typedef_recursive
[rosapi_node-5]     return _get_typedefs_recursive(type, [])
[rosapi_node-5]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 285, in _get_typedefs_recursive
[rosapi_node-5]     typedef = get_typedef(type)
[rosapi_node-5]               ^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 91, in get_typedef
[rosapi_node-5]     type_def = _get_typedef(instance)
[rosapi_node-5]                ^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 149, in _get_typedef
[rosapi_node-5]     fieldnames, fieldtypes, fieldarraylen, examples = _handle_array_information(instance)
[rosapi_node-5]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 178, in _handle_array_information
[rosapi_node-5]     field_type, arraylen = _handle_type_and_array_len(instance, name)
[rosapi_node-5]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 194, in _handle_type_and_array_len
[rosapi_node-5]     field_type = instance._fields_and_field_types[name[1:]]
[rosapi_node-5]                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
[rosapi_node-5] KeyError: 'check_fields'
[ERROR] [rosapi_node-5]: process has died [pid 6530, exit code 1, cmd '/opt/ros/jazzy/lib/rosapi/rosapi_node --ros-args -r __node:=rosapi --params-file /tmp/launch_params_rv4kl86a --params-file /tmp/launch_params_h27onfib --params-file /tmp/launch_params_7_wghq8v'].
```

**Comment by sebabouche** [comment]
I also tried with another type:

```
ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{'type': 'std_msgs/msg/Int32'}"

#> requester: making request: rosapi_msgs.srv.MessageDetails_Request(type='std_msgs/msg/Int32')
```

And got the same error:

```
[rosapi_node-5] /usr/lib/python3/dist-packages/apt/cache.py:215: Warning: W:Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1, W:Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1, W:Target DEP-11 (main/dep11/Components-arm64.yml) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1, W:Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list.d/ros2-latest.list:1 and /etc/apt/sources.list.d/ros2.list:1
[rosapi_node-5]   self._depcache = apt_pkg.DepCache(self._cache)
[rosapi_node-5] Traceback (most recent call last):
[rosapi_node-5]   File "/opt/ros/jazzy/lib/rosapi/rosapi_node", line 329, in <module>
[rosapi_node-5]     main()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/rosapi/rosapi_node", line 321, in main
[rosapi_node-5]     rclpy.spin(node)
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/__init__.py", line 244, in spin
[rosapi_node-5]     executor.spin_once()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 827, in spin_once
[rosapi_node-5]     self._spin_once_impl(timeout_sec)
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 822, in _spin_once_impl
[rosapi_node-5]     raise handler.exception()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/task.py", line 239, in __call__
[rosapi_node-5]     self._handler.send(None)
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 508, in handler
[rosapi_node-5]     await call_coroutine()
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 447, in _execute
[rosapi_node-5]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[rosapi_node-5]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 111, in await_or_execute
[rosapi_node-5]     return callback(*args)
[rosapi_node-5]            ^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/rosapi/rosapi_node", line 228, in get_message_details
[rosapi_node-5]     dict_to_typedef(d) for d in objectutils.get_typedef_recursive(request.type)
[rosapi_node-5]                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 115, in get_typedef_recursive
[rosapi_node-5]     return _get_typedefs_recursive(type, [])
[rosapi_node-5]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 285, in _get_typedefs_recursive
[rosapi_node-5]     typedef = get_typedef(type)
[rosapi_node-5]               ^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 91, in get_typedef
[rosapi_node-5]     type_def = _get_typedef(instance)
[rosapi_node-5]                ^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 149, in _get_typedef
[rosapi_node-5]     fieldnames, fieldtypes, fieldarraylen, examples = _handle_array_information(instance)
[rosapi_node-5]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 178, in _handle_array_information
[rosapi_node-5]     field_type, arraylen = _handle_type_and_array_len(instance, name)
[rosapi_node-5]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rosapi_node-5]   File "/opt/ros/jazzy/lib/python3.12/site-packages/rosapi/objectutils.py", line 194, in _handle_type_and_array_len
[rosapi_node-5]     field_type = instance._fields_and_field_types[name[1:]]
[rosapi_node-5]                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
[rosapi_node-5] KeyError: 'check_fields'
[ERROR] [rosapi_node-5]: process has died [pid 7735, exit code 1, cmd '/opt/ros/jazzy/lib/rosapi/rosapi_node --ros-args -r __node:=rosapi --params-file /tmp/launch_params_g9zs9qyt --params-file /tmp/launch_params_b2kj9cjn --params-file /tmp/launch_params_fo_8woyd'].
```

**Comment by scottbell** [comment]
There's a change in the Python message generator that landed in Iron (and newer distros) that appears to breaking the array handling in rosapi. Iron’s `rosidl_generator_py` templates now inject extra private slots (e.g. [_check_fields](https://github.com/ros2/rosidl_python/blob/iron/rosidl_generator_py/resource/_msg.py.em#L212)) into every message’s `__slots__`. Those names don’t appear in the message’s `_fields_and_field_types` dict, so code that blindly walks `__slots__` will hit a KeyError.

One way to fix this is to alter [objectutils.py](https://github.com/RobotWebTools/rosbridge_suite/blob/ros2/rosapi/src/rosapi/objectutils.py#L197) to skip any slot whose stripped name isn’t in `_fields_and_field_types`, e.g.:
```python
def _handle_array_information(instance):
    """Extracts field names, types, lengths and examples for real message fields."""
    fieldnames, fieldtypes, fieldarraylen, examples = [], [], [], []
    for slot in instance.__slots__:
        # strip leading “_” and skip if not a real field
        key = slot[1:] if slot.startswith("_") else slot
        if key not in instance._fields_and_field_types:
            continue

        fieldnames.append(key)
        field_type, arraylen = _handle_type_and_array_len(instance, slot)
        fieldarraylen.append(arraylen)

        value = getattr(instance, slot)
        fieldtypes.append(_type_name(field_type, value))
        examples.append(str(_handle_example(arraylen, field_type, value)))

    return fieldnames, fieldtypes, fieldarraylen, examples
```

This seems to fix the issue:
```
$ ros2 service call /rosapi/message_details rosapi_msgs/srv/MessageDetails "{'type': 'sensor_msgs/JointState'}"
waiting for service to become available...
requester: making request: rosapi_msgs.srv.MessageDetails_Request(type='sensor_msgs/JointState')

response:
rosapi_msgs.srv.MessageDetails_Response(typedefs=[rosapi_msgs.msg.TypeDef(type='sensor_msgs/JointState', fieldnames=['header', 'name', 'position', 'velocity', 'effort'], fieldtypes=['std_msgs/Header', 'string', 'double', 'double', 'double'], fieldarraylen=[-1, 0, 0, 0, 0], examples=['{}', '[]', '[]', '[]', '[]'], constnames=['SLOT_TYPES', 'effort', 'header', 'name', 'position', 'velocity'], constvalues=['(<rosidl_parser.definition.NamespacedType object at 0xffff8b5b2aa0>, <rosidl_parser.definition.UnboundedSequence object at 0xffff8b5b2ad0>, <rosidl_parser.definition.UnboundedSequence object at 0xffff8b5b2b30>, <rosidl_parser.definition.UnboundedSequence object at 0xffff8b5b2b90>, <rosidl_parser.definition.UnboundedSequence object at 0xffff8b5b2bf0>)', "array('d')", "std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_id='')", '[]', "array('d')", "array('d')"]), rosapi_msgs.msg.TypeDef(type='std_msgs/Header', fieldnames=['stamp', 'frame_id'], fieldtypes=['builtin_interfaces/Time', 'string'], fieldarraylen=[-1, -1], examples=['{}', ''], constnames=['SLOT_TYPES', 'frame_id', 'stamp'], constvalues=['(<rosidl_parser.definition.NamespacedType object at 0xffff8b5efdf0>, <rosidl_parser.definition.UnboundedString object at 0xffff88d4a260>)', '', 'builtin_interfaces.msg.Time(sec=0, nanosec=0)']), rosapi_msgs.msg.TypeDef(type='builtin_interfaces/Time', fieldnames=['sec', 'nanosec'], fieldtypes=['int32', 'uint32'], fieldarraylen=[-1, -1], examples=['0', '0'], constnames=['SLOT_TYPES', 'nanosec', 'sec'], constvalues=['(<rosidl_parser.definition.BasicType object at 0xffff98728eb0>, <rosidl_parser.definition.BasicType object at 0xffff98728e50>)', '0', '0'])])
```

I'll put together a PR to fix this.

**Comment by bjsowa** [comment]
Fixed by #1031
